export const SAVE_EVENT_PROCESSING = 'SAVE_EVENT_PROCESSING';
export const SAVE_EVENT_SUCCESS = 'SAVE_EVENT_SUCCESS';
export const SAVE_EVENT_FAIL = 'SAVE_EVENT_FAIL';

export const PUSH_EVENT_TO_LIST = 'PUSH_EVENT_TO_LIST';

export const FETCH_EVENTS_PROCESSING = 'FETCH_EVENTS_PROCESSING';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_FAIL';
